CREATE TABLE DIM_EMPLOYEE
(EMP_ID INT, EMP_NAME VARCHAR(25), PRIMARY KEY (EMP_ID))

CREATE TABLE DIM_BRANCH
(BRANCH_ID INT, BRANCH_NAME VARCHAR(25), PRIMARY KEY (BRANCH_ID))

CREATE TABLE DIM_PRODUCT
(PROD_ID INT, PROD_NAME VARCHAR(25), PRIMARY KEY (PROD_ID))

CREATE TABLE DIM_CUSTOMER
(CUST_ID INT, CUST_NAME VARCHAR(25), PRIMARY KEY (CUST_ID))

CREATE TABLE FACT_SHOP
(EMP_ID INT,BRANCH_ID INT, PROD_ID INT, CUSTOMER_ID INT)

SELECT @@VERSION
